-- 1
SELECT * FROM COUNTRY
WHERE country LIKE 'A%a';

-- 2
SELECT * FROM COUNTRY
WHERE country LIKE '%_____n'; 

-- 3
SELECT * FROM FILM
WHERE TITLE ~~* '%t%T%T%T%';

-- 4
SELECT * FROM FILM
WHERE (TITLE LIKE 'C%') AND (LENGTH IN (90)) AND (RENTAL_RATE IN (2.99));